# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-28 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0014_knowledgefiledownload_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='drwaid',
            field=models.IntegerField(default=None, verbose_name='画面ID'),
        ),
        migrations.AddField(
            model_name='step',
            name='formula',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='表达式'),
        ),
        migrations.AddField(
            model_name='step',
            name='fromnode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='起点'),
        ),
        migrations.AddField(
            model_name='step',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='高度'),
        ),
        migrations.AddField(
            model_name='step',
            name='intertype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='子类型'),
        ),
        migrations.AddField(
            model_name='step',
            name='left',
            field=models.IntegerField(blank=True, null=True, verbose_name='左边距'),
        ),
        migrations.AddField(
            model_name='step',
            name='sub_process',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='子流程'),
        ),
        migrations.AddField(
            model_name='step',
            name='tonode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='终点'),
        ),
        migrations.AddField(
            model_name='step',
            name='top',
            field=models.IntegerField(blank=True, null=True, verbose_name='上边距'),
        ),
        migrations.AddField(
            model_name='step',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='步骤类型'),
        ),
        migrations.AddField(
            model_name='step',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='宽度'),
        ),
    ]
