# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-09 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0016_step_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='level',
        ),
    ]
