# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0019_auto_20190109_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='rto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RTO'),
        ),
    ]
