# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-10 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0020_processrun_rto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processrun',
            name='rto',
            field=models.IntegerField(blank=True, null=True, verbose_name='RTO'),
        ),
    ]
