# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-15 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0022_auto_20190110_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='场景编号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='场景名称')),
                ('remark', models.CharField(blank=True, max_length=5000, null=True, verbose_name='场景描述')),
                ('business', models.CharField(blank=True, max_length=5000, null=True, verbose_name='影响业务')),
                ('application', models.CharField(blank=True, max_length=5000, null=True, verbose_name='影响应用')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faconstor.Scene', verbose_name='父节点')),
                ('process', models.ManyToManyField(to='faconstor.Process')),
            ],
        ),
    ]
